server:
  port: 8010
  
logging:
  level:
    root: WARN
    org.springframework: INFO
    kr.insoft.batch: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  master:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/master?verifyServerCertificate=false&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
  slave:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/slave?verifyServerCertificate=false&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver